apiVersion: v1
kind: ConfigMap

metadata:
  name: petclinic-config

data:
  SPRING_PROFILES_ACTIVE: "local"
  logging.level.org.springframework: INFO
  spring.web.resources.cache.cachecontrol.max-age: 12h