# k8s/postgres-binding-secret.example.yaml
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db
type: servicebinding.io/postgresql
stringData:
  type: postgresql
  provider: postgresql
  host: postgres
  port: "5432"
  database: petclinic
  username: CHANGE_ME
  password: CHANGE_ME